### PR TITLE
[8.0] sql_report improvment and add abstract model to manage SQL requests

### PR DESCRIPTION
**Pull request by legalsylvain**
* Add new module sql_request_abstract with a model sql.request.mixin
* make sql_report depending on sql_request_abstract, and move some code
* add a new state on sql.report. 'draft' and 'sql checked'. Manage state in sql_report. Not possible to execute a sql_report in a draft state
* FIX, possibility to check SQL request, by executing it in some other modules. (with rollback features)
* IMP : possibility to write a draft request, without checking it
* REF : add a hook, to have the possibility to use database before the roolback. (usefull to analyse table structure)
* ADD possibility to have many modes to have the result of the request. (current mode 'output' to extract 
* IMP : replace one group "editor" by two groups "user" and "manager". user can see all the requests and execute them by default. "manager" can edit and validate requests

### CODE REVIEW

**Comment by florian-dacosta** [comment]
I tried to test the module sql_export, but it fails with demo data : 

  File "/home/florian/dev/test/odoo8/server-tools/sql_export/wizard/wizard_file.py", line 91, in export_sql
    copy_options=sql_export.copy_options)
  File "/home/florian/dev/test/odoo8/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/florian/dev/test/odoo8/server-tools/sql_request_abstract/models/sql_request_mixin.py", line 167, in _execute_sql_request
    self.env.cr.copy_expert(query, output)
ProgrammingError: copy_expert cannot be used with an asynchronous callback.

**Comment by legalsylvain** [comment]
talked with @florian-dacosta. seems that is a environment problem.

**Comment by florian-dacosta** [comment]
I did some tests with sql_export and review the code. It seems all good to me, thank you for the effort Sylvain!
The one thing missing, that we could add later is to implement _prepare_request_check_execution method in sql_export.

**Comment by legalsylvain** [comment]
Thanks for your review. Indeed, I wrote a note in the roadmap section.
[ref](https://github.com/akretion/server-tools/pull/13/files#diff-d60ed6ec902f81e2da7d311b3829cb24R27)
but it's not a regression, this test was already disabled in the current code.

Ok for merging on akretion repository ?

**Pull request merged**
